name: ci_uy.cr
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: ubuntu-latest, crystal: 1.0.0}
    steps:
    - uses: actions/checkout@v2
    - uses: oprypin/install-crystal@v1
      with:
        crystal: ${{matrix.crystal}}
    - name: Run tests
      run: crystal spec
    - name: Check format
      run: crystal tool format --check
